#!/bin/bash
set -e
##################################################################################################################
# Author 	: 	Erik Dubois
# Website : https://www.erikdubois.be
# Website	:	https://www.arcolinux.info
# Website	:	https://www.arcolinux.com
# Website	:	https://www.arcolinuxd.com
# Website	:	https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################
echo "#################################################"
echo "If it feels like the downloads are too slow"
echo "Stop the installation with CTRL + C"
echo "and run the alias - mirror in the terminal"
echo "#################################################"

sudo pacman -Syyu
sudo pacman -S lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings --noconfirm --needed
sudo pacman -S openbox --noconfirm --needed
sudo systemctl enable lightdm.service -f
sudo systemctl set-default graphical.target

if [[ -f `pwd`/sharedfuncs ]]; then
  source sharedfuncs
else
  echo "missing file: sharedfuncs"
  exit 1
fi

install_display_manager() { #{{{
    while true
    do
      print_title "DISPLAY MANAGER - https://wiki.archlinux.org/index.php/Display_Manager"
      print_info "A display manager, or login manager, is a graphical interface screen that is displayed at the end of the boot process in place of the default shell."
      echo " 1) $(menu_item "entrance-git" "Entrance") $AUR"
      echo " 2) $(menu_item "gdm" "GDM")"
      echo " 3) $(menu_item "lightdm" "LightDM")"
      echo " 4) $(menu_item "sddm" "SDDM")"
      echo " 5) $(menu_item "slim" "Slim")"
      echo ""
      echo " b) BACK|SKIP"
      echo ""
      DISPLAY_MANAGER+=" b"
      read_input_options "$DISPLAY_MANAGER"
      for OPT in ${OPTIONS[@]}; do
        case "$OPT" in
          1)
            aur_package_install "entrance-git"
            system_ctl enable entrance
            ;;
          2)
            package_install "gdm"
            system_ctl enable gdm
            ;;
          3)
            if [[ ${KDE} -eq 1 ]]; then
              package_install "lightdm lightdm-kde-greeter"
            else
              package_install "lightdm lightdm-gtk-greeter"
            fi
            system_ctl enable lightdm
            ;;
          4)
            package_install "sddm sddm-kcm"
            system_ctl enable sddm
            sddm --example-config > /etc/sddm.conf
            sed -i 's/Current=/Current=breeze/' /etc/sddm.conf
            sed -i 's/CursorTheme=/CursorTheme=breeze_cursors/' /etc/sddm.conf
            sed -i 's/Numlock=none/Numlock=on/' /etc/sddm.conf
            ;;
          5)
            package_install "slim"
            system_ctl enable slim
            ;;
          "b")
            break
            ;;
          *)
            invalid_option
            ;;
        esac
      done
      source sharedfuncs_elihw
    done
  } #}}}
  install_themes() { #{{{
    while true
    do
      print_title "$1 THEMES"
      echo " 1) $(menu_item "numix-circle-icon-theme-git" "Icons Themes") $AUR"
      echo " 2) $(menu_item "arc-gtk-theme" "GTK Themes")"
      echo ""
      echo " d) DONE"
      echo ""
      THEMES_OPTIONS+=" d"
      read_input_options "$THEMES_OPTIONS"
      for OPT in ${OPTIONS[@]}; do
        case "$OPT" in
          1)
            install_icon_theme
            OPT=1
            ;;
          2)
            install_gtk_theme
            OPT=2
            ;;
          "d")
            break
            ;;
          *)
            invalid_option
            ;;
        esac
      done
      source sharedfuncs_elihw
    done
  } #}}}
  install_misc_apps() { #{{{
      print_title "$1 ESSENTIAL APPS"
            install_display_manager
            package_install "dmenu"
            package_install "feh"
            package_install "viewnior"
            package_install "gmrun"
            package_install "rxvt-unicode"
            aur_package_install "squeeze-git"
            package_install "thunar tumbler"
            package_install "tint2"
            package_install "volwheel"
            package_install "xfburn"
            package_install "xcompmgr transset-df"
            package_install "zathura"
            package_install "speedtest-cli"
#      source sharedfuncs_elihw
  } #}}}

  print_title "DESKTOP ENVIRONMENT|WINDOW MANAGER"
  print_info "A DE provide a complete GUI for a system by bundling together a variety of X clients written using a common widget toolkit and set of libraries.\n\nA window manager is one component of a system's graphical user interface."

   #I3 {{{
      print_title "i3 - https://wiki.archlinux.org/index.php/I3"
      print_info "i3 is a dynamic tiling window manager inspired by wmii that is primarily targeted at developers and advanced users. The stated goals for i3 include clear documentation, proper multi-monitor support, a tree structure for windows, and different modes like in vim."
      package_install "i3"
      package_install "rofi"
      # config xinitrc
      config_xinitrc "i3"
      pause_function
      install_misc_apps "i3"
      install_themes "i3"
      ;;
      #}}}
    13)
      #OPENBOX {{{
      print_title "OPENBOX - http://wiki.archlinux.org/index.php/Openbox"
      print_info "Openbox is a lightweight and highly configurable window manager with extensive standards support."
      package_install "openbox obconf obmenu menumaker"
      package_install "lxappearance"
      package_install "leafpad epdfview nitrogen"
      aur_package_install "openbox-patched"
      mkdir -p /home/${username}/.config/openbox/
      cp /etc/xdg/openbox/{menu.xml,rc.xml,autostart} /home/${username}/.config/openbox/
      chown -R ${username}:users /home/${username}/.config
      # config xinitrc
      config_xinitrc "openbox-session"
      pause_function
      install_misc_apps "OPENBOX"
      install_themes "OPENBOX"
      ;;
      #}}}
      install_desktop_environment
  #COMMON PKGS {{{
    #MTP SUPPORT {{{
    if is_package_installed "libmtp" ; then
      package_install "gvfs-mtp"
    fi
    #}}}
    if [[ ${KDE} -eq 0 ]]; then
      package_install "gvfs gvfs-goa gvfs-afc gvfs-mtp gvfs-google"
      package_install "xdg-user-dirs-gtk"
      package_install "pavucontrol"
      package_install "ttf-bitstream-vera ttf-dejavu"
      aur_package_install "gnome-defaults-list"
      is_package_installed "cups" && package_install "system-config-printer gtk3-print-backends"
      is_package_installed "samba" && package_install "gvfs-smb"
    fi
  #}}}
  #COMMON CONFIG {{{
    # speed up application startup
    mkdir -p ~/.compose-cache
    # D-Bus interface for user account query and manipulation
    system_ctl enable accounts-daemon
    # Improvements
    add_line "fs.inotify.max_user_watches = 524288" "/etc/sysctl.d/99-sysctl.conf"
  #}}}
}
